### ISSUE TITLE
Update to latest Webpack

### ISSUE THREAD

**Issue by cgatian** [synapse-wireless-labs/component-lab#10]
Update Webpack and Webpack-Dev-Server to the latest versions.  Beta is missing some configuration options such as `performance` which throws errors on compilation.

Also, it might be good to make Webpack a peer dependency since the user will be supplying their own webpack.config. Not sure though, haven't used peer dependencies before.

**Comment by isaacplmann** [comment]
I think this PR does it #12

**Comment by cgatian** [comment]
@isaacplmann Yes!!! 👍
