### ISSUE TITLE
module.id undefined in ExperimentBuilder

### ISSUE THREAD

**Issue by cgatian** [synapse-wireless-labs/component-lab#9]
If `undefined` is passed to the `ExperimentBuilder` constructor, an error occurs when it attempts to build a string with the module `id` property (index.ts:ln:21). 

This is probably some sort of misconfiguration on my part.  I've tried adding `module: module.id` to the component decorator, and that didn't fix it.  So I'm assuming its something in with my webpack configuration.

As a workaround I've passed an anonymous object `{id: 'test'}` as the second parameter to the function.

**Comment by isaacplmann** [comment]
I think PR #12 fixes this.

**Comment by cgatian** [comment]
I believe it will! 😄
